add support for rootUrl base url
shastajs/redux-sutro pull request #4
Opened 2017-07-07 23:41 UTC by stevelacy

This adds an optional `rootUrl` parameter:
```js
{
  rootUrl: 'http://api.systems.com'
}

// => http://api.systems.com/table/:id instead of /table/:id
```

2017-07-08 02:35 UTC, yocontra requested changes

2017-07-08 02:35 UTC, contra commented on src/index.js
> +        if (options.rootUrl) return `${options.rootUrl}${template(v.path, opt)}`
use url-join here

2017-07-10 16:03 UTC, stevelacy commented
updated

2017-07-10 18:07 UTC, merged

2017-07-10 18:08 UTC, contra commented
Published